version: '3'
services:
  app:
    build: 
      context: ./server
      dockerfile: Dockerfile.php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9001:80
  db:
      image: mysql
      volumes:
        - ./server/mysql/data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password
